[build]
rustflags = []

[target.aarch64-apple-darwin]
rustflags = []

[env]
CFLAGS = "-I/opt/homebrew/Cellar/harfbuzz/12.2.0_1/include"
CXXFLAGS = "-I/opt/homebrew/Cellar/harfbuzz/12.2.0_1/include -std=c++17"
PKG_CONFIG_PATH = "/opt/homebrew/opt/icu4c@76/lib/pkgconfig"
